### ISSUE TITLE
Stylesheet does not apply

### ISSUE THREAD

**Issue by kelson42** [kiwix/sotoki#5]
I have created a dump at:
http://zimfarm.kiwix.org/sotoki/

There are css/js files, but they seem to not apply to the content. For example at this page:
http://zimfarm.kiwix.org/sotoki/tags.html

**Comment by amirouche** [comment]
This is because i looks for stylesheet at the root of the website eg. `http://zimfarm.kiwix.org/static/main.css`. I will think about it, but last time I choosed this solution because otherwise it requires to keep track of where the rendered page will be located, which is doable, but usually the solution is a) to use single `/` b) to use a prefix domain which must be in a configuration file or else.

a) was simpler.

**Comment by kelson42** [comment]
Why not putting all HTML pages at the same depth:
/tags/...html
/questions/...html
/css

then you alway have to look at the same place

**Comment by amirouche** [comment]
This will lead to a static files layout that is not natural. In the sens that the  html static files will not reflect the website hierarchy... 

I prefer to add an option to specify a root url.

I'm working on it.

**Comment by amirouche** [comment]
I pushed a few cosmetic changes and a fix for this issue. The small inconvenience is that to specify the **root url** one must drop to the plain `sotoki.py` command. Which means that instead of doing:

```
make build-all
```

One must do the steps manually  ie:

```
rm -rf build  # remove the build directory if any
./sotoki.py build templates db/superuser build  --root-url=http://example.com/path/to/sotoki
make copy-static
```

Eventually I'd like to keep the Makefile for building the production files, I'm not sure how to improve that. 

Maybe using an environment variable? WDYT?

**Comment by amirouche** [comment]
I think the environment variable is better and easier to deal with, do you agree?

**Comment by amirouche** [comment]
Actually it will be painful to have several ways to do things. Let's only use command line options.
